[theme]
base = "light"

# Color principal (afecta a botones, barras de progreso y elementos activos)
primaryColor = "#7d192a" # Cambiadlo por el color principal de vuestra paleta

# Color de fondo de la aplicación
backgroundColor = "#d4cfcf" 

# Color de fondo de las áreas secundarias (como el panel lateral)
secondaryBackgroundColor = "#8f9195" # Un gris muy clarito o el color secundario de vuestra marca

# Color del texto
textColor = "#262730" 

# Tipografía: podéis elegir "sans serif", "serif" o "monospace"
font = "sans serif"
